In [1]:
import numpy as np
l1=[1,2,3,4]
arr=np.array([1,2,3,4,5])
print(type(l1))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
arr1=np.arange(1,10,2)
print(arr1)
print(arr1.size)

[1 3 5 7 9]
5


In [9]:
zero_arr=np.zeros((3,3))
print(zero_arr)
ones_arr=np.ones((3,3))
print(ones_arr)
eye_arr=np.eye((3))
print(eye_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
import numpy as np
import time

# Create large data
size = 100000
python_list = list(range(size))
numpy_array = np.arange(size)

# -------- Python List --------
start = time.time()
result_list = [x + 5 for x in python_list]
end = time.time()

print("Python List Time:", end - start)

# -------- NumPy Array --------
start = time.time()
result_numpy = numpy_array + 5
end = time.time()

print("NumPy Time:", end - start)

Python List Time: 0.017264127731323242
NumPy Time: 0.0013446807861328125


In [17]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a**b

array([      1,     128,    6561,  262144, 9765625])

In [8]:
a = np.array([30,55,45])
np.max(a)

np.int64(55)

In [34]:
a = np.array([True,False])
print(a)
a.astype(int)
np.array([1,2,3], dtype='float32')

[ True False]


array([1., 2., 3.], dtype=float32)

In [6]:
np.random.rand(9)

array([0.29128991, 0.27475556, 0.36939968, 0.59262609, 0.2504783 ,
       0.60823929, 0.87512431, 0.47692773, 0.27503183])

In [4]:
A = np.array([1,2,3,4,5])
np.ndim(A)

1

In [135]:
a=np.ones((3,3))
print(a)
a=np.ones((3,3),dtype=int)
print(a)
a=np.ones((3,3),dtype=str)
print(a)
a=np.ones((3,3),dtype=bool)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [136]:
a=np.zeros((3,3))
print(a)
a=np.zeros((3,3),dtype=int)
print(a)
a=np.zeros((3,3),dtype=str)
print(a)
a=np.zeros((3,3),dtype=bool)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[['' '' '']
 ['' '' '']
 ['' '' '']]
[[False False False]
 [False False False]
 [False False False]]


In [137]:
a= np.arange(0,30,3)
print(a)

[ 0  3  6  9 12 15 18 21 24 27]


In [139]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a = np.reshape(a,(4,3))
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [138]:
a = np.array([[1,2,3],[2,4,6]])
a.ravel()

array([1, 2, 3, 2, 4, 6])

In [141]:
a = np.array([[[1,2,3],[2,4,6],[3,6,9]]])
print(a)
np.ndim(a)

[[[1 2 3]
  [2 4 6]
  [3 6 9]]]


3

In [145]:
a = np.array([[[1,2,3],[2,4,6],[3,6,9]]])
a.ravel()

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [148]:
a = np.array([1,2,3,2,4,6,3,6,9])
a = np.reshape(a,(3,3))
print(a)
np.ndim(a)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


2

In [2]:
import numpy as np
a = np.array([[[1,2,3]],[[2,3,4]],[[3,5,8]]])
print(a)
np.ndim(a)

[[[1 2 3]]

 [[2 3 4]]

 [[3 5 8]]]


3

In [7]:
a = np.array([1,2,3,4,5,6,7,8,9])
a = np.reshape(a,(3,3))
print(a)
print(np.ndim(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[2,1])

8


In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[2,1]=4
print(a)

[[1 2 3]
 [4 5 6]
 [7 4 9]]


In [29]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a = np.reshape(a,(3,2,2))
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [9]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a)
a.ravel()

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a[2,1,1])

12


dtype('int64')

In [58]:
a = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])
print(a[0,:,:])
print(a[1,1,:])
print(a[1,1,1])
print(a[:,0,:])
print(a[:,:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[13 14 15]
14
[[ 1  2  3]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]]


In [70]:
a = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])
print(a[0,0:2,:])
print(a[1,:,1:3])
print(a[:,0:2,:])
print(a[:,:,1])
print(a[0,:,1:3])
print(a[0].diagonal())
print(a[0])

[[1 2 3]
 [4 5 6]]
[[11 12]
 [14 15]
 [17 18]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]
[[ 2  5  8]
 [11 14 17]]
[[2 3]
 [5 6]
 [8 9]]
[1 5 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
a = np.array([1,3,5])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+b)

[[ 2  5  8]
 [ 5  8 11]
 [ 8 11 14]]


In [3]:
a = np.full((3,2),5)
print(a)

[[5 5]
 [5 5]
 [5 5]]
